input:
  generate:
    count: 1
    interval: 60s
    mapping: 'root = {}'

pipeline:
  processors:
    - branch:
        request_map: 'root = {}'
        processors:
          - http:
              url: "http://elasticsearch-6.8:9200/_alias/ggg"
              verb: GET
              headers:
                Content-Type: application/json
              retries: 3
              timeout: 5s
          - catch:
            - log:
                level: WARN
                message: "alias does not exist"
            - mapping: 'root = deleted()'
        result_map: |
          root.success = this

output:
  stdout: {}
