input:
  http_client:
    url: https://api.chucknorris.io/jokes/random
    verb: GET
    headers:
      Content-Type: application/json

pipeline:
  processors:
    - mapping: |
        meta first_word = this.value.split(" ").index(0).lowercase()
        meta full_joke = this.value
        root = this
    - branch:
        request_map: |
          root = {}
        processors:
          - http:
              url: "http://elasticsearch-6.8:9200/${!meta(\"first_word\")}/_alias"
              verb: GET
        result_map: |
          meta alias_exists = this.status_code == 200
    - log:
        message: "Alias exists: ${!meta(\"alias_exists\")} || First word: ${!meta(\"first_word\")} || Full joke: ${!meta(\"full_joke\") }"

    # Correctly formatted switch processor
    - switch:
        cases:
          - check: 'meta("alias_exists") == true'
            output:
              elasticsearch:
                urls:
                  - "http://elasticsearch-6.8:9200/"
                index: "${!meta(\"first_word\")}"
                type: "_doc"
                id: "${!uuid_v4()}"
          - check: 'meta("alias_exists") == false'
            output:
              log:
                message: "Skipping output to Elasticsearch as alias '${!meta(\"first_word\")}' does not exist."

logger:
  level: INFO
