input:
  generate:
    count: 1
    mapping: 'root = {}'

pipeline:
  processors:
    - catch:
        - http:
#            url: "http://elasticsearch-6.8:9200/_alias/jokes"
            url: "http://elasticsearch-6.8:9200/_alias/ggg"
            verb: "GET"
            headers:
              Accept: "application/json"
              Content-Type: "application/json"

    - bloblang: |
        root.alias_exists = if meta("http_status_code") == 404 {
            false
        } else if meta("http_status_code") == 200 {
            true
        } else {
            false
        }

    - log:
        message: |
          alias 'jokes' exists: ${! json("alias_exists") } | http_status_code: ${!meta("http_status_code")}

output:
  stdout: {}
