input:
  http_client:
    url: https://api.chucknorris.io/jokes/random
    verb: GET
    headers:
      Content-Type: application/json

pipeline:
  processors:
    - mapping: |
        meta first_word = this.value.split(" ").index(0).lowercase()
        meta full_joke = this.value
        root = this
    - log:
        message: "First word: ${! meta(\"first_word\") } || Full joke: ${! meta(\"full_joke\") }"

output:
  elasticsearch:
    urls:
      - "http://elasticsearch-6.8:9200/"
    index: "${!meta(\"first_word\")}"
    type: "_doc"
    id: "${!uuid_v4()}"

logger:
  level: INFO      
    
