pipeline:
  processors:
    - branch:
        processors:
          - log:
              message: "Builing PUT command"
          - bloblang: |
              root = {
                "actions": [
                  {
                    "add": {
                      "index": "norman",
                      "alias": "norman_a"
                    }
                  }
                ]
              }
          - http:
              url: "http://elasticsearch-6.8:9200/_aliases"
              verb: PUT
              headers:
                Content-Type: "application/json"
              max_retry_backoff: 5s
              retries: 3
        result_map: ""

logger:
  level: INFO

