input:
  generate:
    count: 1
    interval: 60s
    mapping: 'root = {}'

pipeline:
  processors:
    - branch:
        request_map: 'root = {"actions": [{"add": {"index": "norman", "alias": "norman_a"}}]}'
        processors:
          - http:
              url: "http://elasticsearch-6.8:9200/_aliases"
              verb: POST
              headers:
                Content-Type: application/json
              retries: 3        # Compatible in Benthos 4.24 for retry attempts
              timeout: 5s
        result_map: 'root = this'

output:
  stdout: {}
