input:
  generate:
    count: 1
    interval: 60s
    mapping: 'root = {}'

pipeline:
  processors:
    - http:
        url: "http://elasticsearch-6.8:9200/_cat/aliases/jack_a?h=alias"
        verb: GET
        headers:
          Content-Type: application/json
        retries: 3
        timeout: 5s
        result_map: 'root.alias_exists = this'

    - branch:
        conditions:
          - check: "root.alias_exists == ''"
        processors:
          - http:
              url: "http://elasticsearch-6.8:9200/jack-000001"
              verb: PUT
              headers:
                Content-Type: application/json
              retries: 3
              timeout: 5s
              request_map: 'root = {"settings": {"number_of_shards": 1, "number_of_replicas": 1}}'

          - http:
              url: "http://elasticsearch-6.8:9200/_aliases"
              verb: POST
              headers:
                Content-Type: application/json
              retries: 3
              timeout: 5s
              request_map: 'root = {"actions": [{"add": {"index": "jack-000001", "alias": "jack_a", "is_write_index": true}}]}'

        result_map: 'root = this'

output:
  stdout: {}
