input:
  generate:
    count: 1
    interval: 60s
    mapping: 'root = {}'

pipeline:
  processors:
    - http:
        url: "http://elasticsearch-6.8:9200/_alias/ggg_"
        verb: GET
        headers:
          Content-Type: application/json
        retries: 3
        timeout: 5s
        result_map: 'root.response = this'

    - fallback:
        processors:
          - check:
              conditions:
                - status_code: 404
              true_processors:
                - set:
                    path: 'root.error'
                    value: 'Alias not found.'
              false_processors:
                - set:
                    path: 'root.success'
                    value: 'Successfully retrieved alias.'
                - set:
                    path: 'root.data'
                    value: 'root.response'

output:
  stdout: {}
