input:
  generate:
    interval: "100ms"
    count: 4
    mapping: |
      root.key = if count("key_counter") % 3 == 0 {
        "hello "
      } else {
        "there "
      }

      root.content = uuid_v4()
      root.team_info = "bojack " + uuid_v4()

pipeline:
  processors:
    - bloblang: |
        let MAX_OUTPUT = 3
        root = this

        let iLine_number = count("line_counter")
        let sLine_number = $iLine_number.string()
        # root.row_id = $sLine_number
        root.row_id = $iLine_number

        if $iLine_number <= $MAX_OUTPUT {
          root.filter = "in"
        } else {
          # deleted()
          root.filter = "out"
          root = ""
        }

        
output:
  broker:
    pattern: fan_out
    outputs:
      - stdout:
          codec: lines
